# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: shell

# Linux compability issue.
# Need to build in xenial with lazarus 1.8.2.
# Do not use bionic or newer Lazarus version

# For linux headless.
# See travis_unit_test.sh will install and use xvfb-run
#services: (- xvfb) does not work must use xvfb-run

jobs:
  include:
    - name: Ubuntu 16.04 AMD64 (1.8.2)
      os: linux
      dist: xenial
      env: LAZ_VER=1.8.2 RELEASE_ZIP_FILE="trackereditor_linux_amd64.zip"
    - name: Ubuntu 16.04 AArch64 (1.6)
      os: linux
      dist: xenial
      arch: arm64
      env: LAZ_PKG=true RELEASE_ZIP_FILE="trackereditor_linux_AArch64.zip"
    - name: macOS 10.14 (PKG)
      os: osx
      osx_image: xcode11.3
      env: LAZ_PKG=true LAZ_OPT="--widgetset=cocoa" RELEASE_ZIP_FILE="trackereditor_macOS.zip"
    - name: Windows (2.0.8) Build 32-bit software
      os: windows
      env: LAZ_VER=2.0.8 LAZ_REL=64 LAZ_OPT="--os=win32 --cpu=i386" RELEASE_ZIP_FILE="trackereditor_win32.zip"

before_install:
# Install python in windows OS
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install python3 --params "/InstallDir:C:\python3"; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=/c/Python3:/c/Python3/Scripts:/c/lazarus:$PATH; fi

install:
# Output something at regular time or Travis will kills the job
- while sleep 60; do echo "===== 1 minute mark ====="; done &
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python ./travis-lazarus/.travis.install.py; fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./travis-lazarus/.travis.install.py; fi
# Killing background sleep loop
- kill %1

script:
# Output something at regular time or Travis will kill the job
  - echo "start script"
  - while sleep 60; do echo "===== 1 minute mark ====="; done &

# Build trackereditor project (Release mode)
  - lazbuild --build-mode=Release $LAZ_OPT $PROJECT_LPI_EDITOR_PATH

# Build unit test project (Debug mode)
  - lazbuild --build-mode=Debug $LAZ_OPT $PROJECT_LPI_UNIT_TEST_PATH

# Start the unit test
  - source ./scripts/travis_unit_test.sh

# Killing background sleep loop
  - kill %1

before_deploy:
# Create the zip file for deployment
  - source ./scripts/travis_deploy.sh

deploy:
  - provider: releases
    prerelease: false
    cleanup: false
    edge: true # opt in to dpl v2
    token:
      secure: hmjev+YIClSOec6wMclUv5W4lgyLpdX7DlUpF2LQ1W/EO/x/b8RzmSPjNZ5sa7IDUe1WoVXm89G6HtkGGHcRqJrZjNn18HvpvEOnIYgIEXBVtW9uaURsSJ2LYve9beHHvYzs0doEQp1I24qTENUOqMABStk7MKRTATZ7nBWIinZVkpojEYIizQtCnUWwJXpzgs9mx7BEAVqLJPJ35oXNVjEgE96gsWMaYuX82BsVpL9VjGIaYpbEc1iBFBr2RHTgHG03H+2wBewJ4gh3hFwq9vt6mEqdC6Y9UIqmAEUMzCpokqrIfV2cfnPe24miPqmCLboua7Ddu8OpLj/yQ9DvC8xVEVh8aiGszzPvnytaFuRfLxI5HdAtUkA/9P3dXwjJKLJs568kyCTz4Tk7Icrb7seS1i84BJs3Vp2/lkmqDRDR0OqVGTczZGsxfTK+iaZJaNXb999BmGBw+xnPuG1lgrjHUYyEH2ha9D/9eOXiQfxdKUktPs1cF0II7uv5Cg3LEcFyN/A7jblNpM5B9cnf5kJ13lbpqL+Eyig90b9Q9YsrwGGOqtXJG+jSqXOv0O9/warFJfadA0avJljOFv4Pxl4tYe73EA/gP1GVG5UVC/F9nWZhUzP1kPCjzTzHoYBDCmHf8/GErdpCtibqRHoMIelrbcpe0jr+j5aNPxnTKAc=
    file: "${RELEASE_ZIP_FILE}"
    on:
      tags: true
      repo: GerryFerdinandus/bittorrent-tracker-editor
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "bittorrent-tracker-editor"
    cleanup: false
    region: eu-central-1
    local_dir: s3
    edge: true # opt in to dpl v2
    on:
      branch: to_be_deleted_unit_test
