# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

# Suppress the warning with the online Travis WebLint
language: generic

sudo: required
dist: precise
#trusty does not work in this configuration

os:
  - linux
  - osx

env:
  global:
    - LPIEDITORPATH=source/project/tracker_editor
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:	#For linux and mac osx build
    - LAZ_VER=1.6.2

matrix:		#For windows build with linux wine. Use the same lazarus version as linux/mac build.
  include:
    - os: linux
      env: LAZ_VER=1.6.2  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"

before_install:
    # Start virtual display server
  - sh -e /etc/init.d/xvfb start || true

install:
    # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./travis-lazarus/.travis.install.py

script:
  - lazbuild $LAZ_OPT $LPIEDITORPATH/trackereditor.lpi      # Build trackereditor project

before_deploy:
  - source ./scripts/travis_deploy.sh

deploy:
  provider: releases
  prerelease: false
  skip_cleanup: true
  api_key:
    secure: "s2OquTSTFNECWme15GLuLHGykXQK9Q/ie38eI8wwzPZUQ3WCFJxYRGrR6XSaFWe/VfjNlDTfPaUsKfo4Fi9atOec1fp7ewA9JNnFUclw38o9UHirDYgzDNQD8BMhXXMaaxvYJBT+aN3CFvaBkkTyIb8jYO6RsvHfBQmOb6B//Fl2IFAgI/j8+qUKVtZWYEezGUCMCKZ+r/sFgfK91DsKtH7T51WVrJ9oI/HvvGISw6K1sG0X56LZry/shy8f3NPvGfFofooZ/9uPUamDmZwNR7YR91P10cykihZnarPDbCaCAD77D+AeFSDpcRyusr07dRfqIqNFQ1Hcu3GMIZL2W1dfGdZ9z0PJWQcMZQtwmjimV+2cEgIQTCvmG1wzbOTOW4T9QnDFB72M5njcxd1RYlVJwXq3SgSN1smQzRfArUd1bFeD0crGQ4urhfU12CJ50isgXXgXrOT7RclWUR2i1QISFS2ISDtGuCyh1vSGjVPQ9RSYSgG7/OufwdUXA/ZyK2mFpbZ0iKGNEYtZaL8/ZQMM9KlkyWPoQaSve/zTs+D3N5rFcOfQ7EHAAPTzz/fjpU7Yd3a0yf4pLSpr+ConVw1Kwc7d3VYSsoxhnLp2fgij+Xs/skRud8PLiOUsk8L3hUMS4p9X4ANkE181aQTAmzv7qc6qtXOSkhpzsIIxWGY="
  file: "${RELEASE_ZIP_FILE}"
  on:
    tags: true 
    repo: GerryFerdinandus/bittorrent-tracker-editor

git:
  depth: 1
